name = "Weaving"
license = "MIT"
licenselink = "https://raw.githubusercontent.com/michaelboyles/weaving-theme/master/LICENSE"
description = "Clean, content-focused personal blog theme"
homepage = "https://github.com/michaelboyles/weaving-theme"
tags = ["blog", "responsive"]
features = ["some", "awesome", "features"]
min_version = "0.59.1"

[author]
    name = "Michael Boyles"
    homepage = "https://boyl.es"
